import { useState } from 'react';
import { Plus, Trash2, Image as ImageIcon, Tag } from 'lucide-react';
import { useIngredientStore, type Ingredient } from '../store/ingredientStore';
import { uploadIngredientImage } from '../services/api';
import { cn } from '../lib/utils';
import { supabase } from '../lib/supabase';

export function IngredientsTab() {
    const { ingredients, addIngredient, removeIngredient, selectedIngredientId, selectIngredient } =
        useIngredientStore();
    const [isAddingNew, setIsAddingNew] = useState(false);
    const [newIngredient, setNewIngredient] = useState({
        tag: '',
        name: '',
        type: 'character' as Ingredient['type'],
    });
    const [uploadingImages, setUploadingImages] = useState<File[]>([]);

    const handleImageUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
        const files = Array.from(e.target.files || []);
        setUploadingImages(files);
    };

    const handleSaveIngredient = async () => {
        if (!newIngredient.tag || !newIngredient.name) return;

        try {
            // Upload images
            const uploadedUrls = await Promise.all(
                uploadingImages.map((file) => uploadIngredientImage(file))
            );

            const ingredientData = {
                // id: Generated by DB or we generate UUID? 
                // Let's rely on DB ID if possible, or generate one.
                // Since store needs ID immediately, generating locally or waiting for DB return is best.
                // Let's generate locally for optimistic UI or wait.
                // Implementation plan says "create new UI panel", "upload images". 
                // I'll insert into DB and use returned ID.

                tag: newIngredient.tag.startsWith('@') ? newIngredient.tag : `@${newIngredient.tag}`,
                name: newIngredient.name,
                type: newIngredient.type,
                reference_images: uploadedUrls.map((res) => res.url),
                // created_at: handled by DB default
            };

            const { data, error } = await supabase
                .from('ingredients')
                .insert(ingredientData)
                .select()
                .single();

            if (error) throw error;

            // Store update will happen via Realtime subscription in useIngredients hook!
            // But for immediate feedback/optimistic update:
            const newIng: Ingredient = {
                id: data.id,
                tag: data.tag,
                name: data.name,
                type: data.type,
                referenceImages: data.reference_images,
                createdAt: data.created_at,
            };
            addIngredient(newIng);

            // Reset
            setIsAddingNew(false);
            setNewIngredient({ tag: '', name: '', type: 'character' });
            setUploadingImages([]);
        } catch (error) {
            console.error('Failed to save ingredient:', error);
        }
    };

    return (
        <div className="space-y-6">
            <div className="flex items-center justify-between">
                <div>
                    <h3 className="text-lg font-semibold mb-2">Asset Vault</h3>
                    <p className="text-sm text-white/60">Manage reusable characters, objects, and styles</p>
                </div>
                <button
                    onClick={() => setIsAddingNew(!isAddingNew)}
                    className="glass-panel-hover p-2 rounded-lg"
                >
                    <Plus className="w-5 h-5" />
                </button>
            </div>

            {/* Add New Ingredient Form */}
            {isAddingNew && (
                <div className="glass-panel p-4 space-y-4">
                    <h4 className="font-semibold text-sm">New Ingredient</h4>

                    <div className="space-y-2">
                        <label className="text-xs font-medium">Tag (for prompts)</label>
                        <div className="flex items-center gap-2">
                            <span className="text-purple-400">@</span>
                            <input
                                type="text"
                                value={newIngredient.tag.replace('@', '')}
                                onChange={(e) =>
                                    setNewIngredient({ ...newIngredient, tag: e.target.value.replace('@', '') })
                                }
                                placeholder="Hero"
                                className="flex-1 px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-purple-500"
                            />
                        </div>
                    </div>

                    <div className="space-y-2">
                        <label className="text-xs font-medium">Name</label>
                        <input
                            type="text"
                            value={newIngredient.name}
                            onChange={(e) => setNewIngredient({ ...newIngredient, name: e.target.value })}
                            placeholder="Main Character"
                            className="w-full px-3 py-2 bg-white/5 border border-white/10 rounded-lg text-sm focus:outline-none focus:ring-2 focus:ring-purple-500"
                        />
                    </div>

                    <div className="space-y-2">
                        <label className="text-xs font-medium">Type</label>
                        <div className="grid grid-cols-2 gap-2">
                            {(['character', 'object', 'style', 'location'] as const).map((type) => (
                                <button
                                    key={type}
                                    onClick={() => setNewIngredient({ ...newIngredient, type })}
                                    className={cn(
                                        'py-2 px-3 rounded-lg text-xs font-medium capitalize transition-all',
                                        newIngredient.type === type
                                            ? 'bg-purple-500 text-white'
                                            : 'bg-white/5 hover:bg-white/10'
                                    )}
                                >
                                    {type}
                                </button>
                            ))}
                        </div>
                    </div>

                    <div className="space-y-2">
                        <label className="text-xs font-medium">Reference Images</label>
                        <label className="block cursor-pointer">
                            <div className="glass-panel border border-dashed border-white/20 py-8 text-center hover:bg-white/5 transition-all">
                                <ImageIcon className="w-6 h-6 mx-auto mb-2 text-purple-400" />
                                <p className="text-xs text-white/60">Click to upload images</p>
                            </div>
                            <input
                                type="file"
                                multiple
                                accept="image/*"
                                onChange={handleImageUpload}
                                className="hidden"
                            />
                        </label>
                        {uploadingImages.length > 0 && (
                            <p className="text-xs text-white/60">{uploadingImages.length} image(s) selected</p>
                        )}
                    </div>

                    <div className="flex gap-2">
                        <button
                            onClick={handleSaveIngredient}
                            disabled={!newIngredient.tag || !newIngredient.name}
                            className="flex-1 py-2 bg-purple-500 hover:bg-purple-600 disabled:opacity-50 disabled:cursor-not-allowed rounded-lg text-sm font-medium transition-all"
                        >
                            Save
                        </button>
                        <button
                            onClick={() => {
                                setIsAddingNew(false);
                                setNewIngredient({ tag: '', name: '', type: 'character' });
                                setUploadingImages([]);
                            }}
                            className="flex-1 py-2 glass-panel hover:bg-white/10 rounded-lg text-sm font-medium transition-all"
                        >
                            Cancel
                        </button>
                    </div>
                </div>
            )}

            {/* Ingredients Grid */}
            <div className="space-y-3">
                {ingredients.length === 0 ? (
                    <div className="glass-panel py-12 text-center">
                        <Tag className="w-12 h-12 mx-auto mb-3 opacity-30" />
                        <p className="text-sm text-white/60">No ingredients yet</p>
                        <p className="text-xs text-white/40 mt-1">Add your first asset to get started</p>
                    </div>
                ) : (
                    ingredients.map((ingredient) => (
                        <div
                            key={ingredient.id}
                            className={cn(
                                'glass-panel p-4 cursor-pointer transition-all',
                                selectedIngredientId === ingredient.id
                                    ? 'ring-2 ring-purple-500 bg-purple-500/10'
                                    : 'hover:bg-white/5'
                            )}
                            onClick={() => selectIngredient(ingredient.id)}
                        >
                            <div className="flex items-start justify-between">
                                <div className="flex-1">
                                    <div className="flex items-center gap-2 mb-1">
                                        <span className="text-purple-400 font-mono font-semibold">{ingredient.tag}</span>
                                        <span className="text-xs px-2 py-0.5 glass-panel rounded-full capitalize">
                                            {ingredient.type}
                                        </span>
                                    </div>
                                    <p className="text-sm text-white/80">{ingredient.name}</p>
                                    <p className="text-xs text-white/40 mt-1">
                                        {ingredient.referenceImages.length} reference image(s)
                                    </p>
                                </div>
                                <button
                                    onClick={(e) => {
                                        e.stopPropagation();
                                        removeIngredient(ingredient.id);
                                    }}
                                    className="glass-panel-hover p-2 rounded-lg text-red-400 hover:text-red-300"
                                >
                                    <Trash2 className="w-4 h-4" />
                                </button>
                            </div>
                        </div>
                    ))
                )}
            </div>
        </div>
    );
}
